name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Publish Docker Image"]  # Name of your build workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl rollout status deployment/flask-cont-app --timeout=120s
