name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0, v2.0

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-cont-app:${{ github.ref_name }} \
                 -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-cont-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-cont-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-cont-app:latest

